### ISSUE TITLE
[Question] Issue upgrading to Koin 3.2

### ISSUE THREAD

**Issue by alejandro-rios** [InsertKoinIO/koin-getting-started#1]
Hello :wave:,  I've try to migrate from Koin 3.1.5 to 3.2.0, I've changed some declarations in our modules from `single { }` to `singleOf()` and from `viewModel { }` to `viewModelOf()` but after clean and run the app I'm getting this error:

`java.lang.NoClassDefFoundError: Failed resolution of: Lorg/koin/dsl/ModuleKt;
        at com.metamap.sdk_components.di.AppModuleKt.<clinit>(AppModule.kt:26)
        at com.metamap.sdk_components.di.AppModuleKt.getApplicationModule(AppModule.kt:26)
        at com.metamap.metamap_sdk.SdkStartUpProvider.<init>(SdkStartUpProvider.kt:25)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:121)
        at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:67)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6380)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.koin.dsl.ModuleKt" on path:...`

any idea of what am I missing? I think it may be something missing from the documentation, but I'm not sure.

**Comment by alejandro-rios** [comment]
My bad, I post this in the wrong place 😅
